apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mongo-pvc
  hostPath:
    path: /tmp/db