apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}-svc
spec:
  selector:
    app: {{ .Values.label }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer